
package com.example.soapEjercicioWsdlImport.mx.izzi.service.pkm_querymanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.CreateAdjustmentRequestType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.CreateAdjustmentResponseType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetBalanceRequestType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetBalanceResponseType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetPaymentReverseAdjustmentRequestType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetPaymentReverseAdjustmentResponseType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetPaymentVsRechargeRequestType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetPaymentVsRechargeResponseType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetProductsRequestType;
import com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.GetProductsResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PKM_QueryManagementPortType", targetNamespace = "http://www.izzi.mx/Service/PKM_QueryManagement")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.example.soapEjercicioWsdlImport.mx.izzi.schema.pkm_querymanagement.ObjectFactory.class
})
public interface PKMQueryManagementPortType {


    /**
     * 
     * @param getBalanceReq
     * @return
     *     returns mx.izzi.schema.pkm_querymanagement.GetBalanceResponseType
     */
    @WebMethod(action = "getBalance")
    @WebResult(name = "getBalanceResponse", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getBalanceRes")
    public GetBalanceResponseType getBalance(
        @WebParam(name = "getBalanceRequest", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getBalanceReq")
        GetBalanceRequestType getBalanceReq);

    /**
     * 
     * @param getPaymentVsRechargeReq
     * @return
     *     returns mx.izzi.schema.pkm_querymanagement.GetPaymentVsRechargeResponseType
     */
    @WebMethod(action = "getPaymentVsRecharge")
    @WebResult(name = "getPaymentVsRechargeResponse", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getPaymentVsRechargeRes")
    public GetPaymentVsRechargeResponseType getPaymentVsRecharge(
        @WebParam(name = "getPaymentVsRechargeRequest", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getPaymentVsRechargeReq")
        GetPaymentVsRechargeRequestType getPaymentVsRechargeReq);

    /**
     * 
     * @param createAdjustmentReq
     * @return
     *     returns mx.izzi.schema.pkm_querymanagement.CreateAdjustmentResponseType
     */
    @WebMethod(action = "createAdjustment")
    @WebResult(name = "createAdjustmentResponse", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "createAdjustmentRes")
    public CreateAdjustmentResponseType createAdjustment(
        @WebParam(name = "createAdjustmentRequest", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "createAdjustmentReq")
        CreateAdjustmentRequestType createAdjustmentReq);

    /**
     * 
     * @param getProductsReq
     * @return
     *     returns mx.izzi.schema.pkm_querymanagement.GetProductsResponseType
     */
    @WebMethod(action = "getProducts")
    @WebResult(name = "getProductsResponse", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getProductsRes")
    public GetProductsResponseType getProducts(
        @WebParam(name = "getProductsRequest", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getProductsReq")
        GetProductsRequestType getProductsReq);

    /**
     * 
     * @param getPaymentsReverseAdjustmentReq
     * @return
     *     returns mx.izzi.schema.pkm_querymanagement.GetPaymentReverseAdjustmentResponseType
     */
    @WebMethod(action = "getPaymentsReverseAdjustment")
    @WebResult(name = "getPaymentsReverseAdjustmentResponse", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getPaymentsReverseAdjustmentRes")
    public GetPaymentReverseAdjustmentResponseType getPaymentsReverseAdjustment(
        @WebParam(name = "getPaymentsReverseAdjustmentRequest", targetNamespace = "http://www.izzi.mx/Schema/PKM_QueryManagement", partName = "getPaymentsReverseAdjustmentReq")
        GetPaymentReverseAdjustmentRequestType getPaymentsReverseAdjustmentReq);

}
