
package com.example.soapEjercicioWsdlImport.mx.izzi.service.pkm_querymanagement;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PKM_QueryManagementBindingQSService", targetNamespace = "http://www.izzi.mx/Service/PKM_QueryManagement", wsdlLocation = "https://www.izzi.mx/queryManagement_tst?wsdl")
public class PKMQueryManagementBindingQSService
    extends Service
{

    private final static URL PKMQUERYMANAGEMENTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PKMQUERYMANAGEMENTBINDINGQSSERVICE_EXCEPTION;
    private final static QName PKMQUERYMANAGEMENTBINDINGQSSERVICE_QNAME = new QName("http://www.izzi.mx/Service/PKM_QueryManagement", "PKM_QueryManagementBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.izzi.mx/queryManagement_tst?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PKMQUERYMANAGEMENTBINDINGQSSERVICE_WSDL_LOCATION = url;
        PKMQUERYMANAGEMENTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public PKMQueryManagementBindingQSService() {
        super(__getWsdlLocation(), PKMQUERYMANAGEMENTBINDINGQSSERVICE_QNAME);
    }

    public PKMQueryManagementBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PKMQUERYMANAGEMENTBINDINGQSSERVICE_QNAME, features);
    }

    public PKMQueryManagementBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, PKMQUERYMANAGEMENTBINDINGQSSERVICE_QNAME);
    }

    public PKMQueryManagementBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PKMQUERYMANAGEMENTBINDINGQSSERVICE_QNAME, features);
    }

    public PKMQueryManagementBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PKMQueryManagementBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PKMQueryManagementPortType
     */
    @WebEndpoint(name = "PKM_QueryManagementBindingQSPort")
    public PKMQueryManagementPortType getPKMQueryManagementBindingQSPort() {
        return super.getPort(new QName("http://www.izzi.mx/Service/PKM_QueryManagement", "PKM_QueryManagementBindingQSPort"), PKMQueryManagementPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PKMQueryManagementPortType
     */
    @WebEndpoint(name = "PKM_QueryManagementBindingQSPort")
    public PKMQueryManagementPortType getPKMQueryManagementBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.izzi.mx/Service/PKM_QueryManagement", "PKM_QueryManagementBindingQSPort"), PKMQueryManagementPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PKMQUERYMANAGEMENTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw PKMQUERYMANAGEMENTBINDINGQSSERVICE_EXCEPTION;
        }
        return PKMQUERYMANAGEMENTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
